// ================================================================
//  scene-config.js  —  generated by WebAR Editor
//  Edit in editor.html or directly here.
//  Do not rename this file.
// ================================================================

const SCENE_CONFIG = {

  territory: {
    "name": "Pilar d'amor",
    "description": "Place anchor by your feet"
},

  objects: [
    {
        id: "obj_6",
        src: "symbols/0021 - orgdem.gif",
        w: 0.25,
        h: 0.25,
        pos: {
            x: -0.3,
            y: 0.88,
            z: -0.89
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "float",
                amp: 0.005,
                duration: 2.5,
                ease: "sine",
                axis: "x"
            },
            {
                type: "rotate",
                degreesX: -40,
                degreesZ: 40,
                duration: 2,
                ease: "sine",
                loop: true
            },
            {
                type: "rotate",
                degreesY: 25,
                degreesZ: 20,
                duration: 3.82,
                ease: "sine",
                loop: true
            },
            {
                type: "move",
                axis: "y",
                speed: 0.05,
                direction: 1
            }
        ]
    },
    {
        id: "obj_7",
        src: "symbols/0021 - orgdem.gif",
        w: 0.25,
        h: 0.25,
        pos: {
            x: 1.029,
            y: 1.28,
            z: 0.064
        },
        rotation: {
            x: 130,
            y: 60,
            z: 0
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "float",
                amp: 0.1,
                duration: 6,
                ease: "sine",
                pause: 0.1,
                direction: -1
            },
            {
                type: "float",
                amp: 0.005,
                duration: 2.3,
                ease: "sine",
                axis: "x",
                delay: 0.3,
                direction: -1
            },
            {
                type: "rotate",
                degreesX: 40,
                degreesZ: 6,
                duration: 2,
                ease: "sine",
                loop: true,
                delay: 0.5
            },
            {
                type: "rotate",
                degreesY: 25,
                degreesZ: 20,
                duration: 3.82,
                ease: "sine",
                loop: true
            },
            {
                type: "move",
                axis: "y",
                speed: 0.05,
                delay: 0.1
            }
        ]
    },
    {
        id: "obj_9",
        src: "symbols/0105 - aphoon.gif",
        w: 0.4,
        h: 0.4,
        pos: {
            x: 0.7,
            y: 1,
            z: 0.71
        },
        rotation: {
            x: 12,
            y: 0,
            z: 30
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "spin",
                degrees: 360,
                duration: 6,
                axis: "y",
                ease: "sine",
                mode: "oscillate",
                delay: 0.6,
                direction: -1
            },
            {
                type: "drift",
                amp: 0.009,
                duration: 2,
                axis: "y",
                ease: "sine",
                direction: -1
            },
            {
                type: "rotate",
                degreesX: 50,
                degreesY: -20,
                duration: 1.5,
                ease: "sine",
                loop: true
            },
            {
                type: "move",
                axis: "y",
                speed: 0.09,
                direction: 1
            }
        ]
    },
    {
        id: "obj_10",
        src: "symbols/0134 - erear.gif",
        w: 0.25,
        h: 0.25,
        pos: {
            x: 0.9,
            y: 1.2,
            z: 0
        },
        rotation: {
            x: -100,
            y: 200,
            z: 200
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "move",
                axis: "y",
                speed: 0.05,
                direction: 1,
                duration: 2,
                delay: 0.4,
                ease: "none"
            },
            {
                type: "spin",
                degrees: 360,
                duration: 8.87,
                axis: "y",
                ease: "none",
                direction: -1
            },
            {
                type: "rotate",
                degreesX: 10,
                degreesZ: -20,
                duration: 5,
                ease: "sine",
                loop: true,
                delay: 0.4,
                hold: 0.3
            }
        ]
    },
    {
        id: "obj_11",
        src: "symbols/0014 - benrod.gif",
        w: 0.25,
        h: 0.25,
        pos: {
            x: 0,
            y: 1.4,
            z: 1
        },
        rotation: {
            x: -100,
            y: 200,
            z: 200
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "move",
                axis: "y",
                speed: 0.05,
                direction: -1,
                pause: 0.3,
                duration: 2,
                delay: 0.4,
                ease: "sine"
            },
            {
                type: "spin",
                degrees: 360,
                duration: 10,
                axis: "y",
                ease: "none",
                direction: -1
            },
            {
                type: "rotate",
                degreesX: -90,
                duration: 2,
                ease: "sine",
                loop: true,
                delay: 0.4,
                hold: 0.3
            }
        ]
    },
    {
        id: "obj_13",
        src: "symbols/0308 - ækoj.gif",
        w: 0.25,
        h: 0.25,
        pos: {
            x: -0.9132938156496874,
            y: 0.897393771720105,
            z: -0.1450884619719143
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "move",
                axis: "x",
                speed: 0.05,
                direction: -1,
                delay: 0.8,
                duration: 2,
                pause: 1.25
            },
            {
                type: "move",
                axis: "y",
                speed: 0.05,
                delay: 0.8,
                duration: 2,
                pause: 1.25
            },
            {
                type: "spin",
                degrees: 360,
                duration: 9,
                axis: "y",
                ease: "none"
            },
            {
                type: "spin",
                degrees: 360,
                duration: 30,
                axis: "z",
                ease: "none"
            }
        ]
    },
    {
        id: "obj_14",
        src: "symbols/0228 - boloop.gif",
        w: 0.25,
        h: 0.25,
        pos: {
            x: 0.17172547759115045,
            y: 0.5780975477148752,
            z: -1
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "breathe",
                amp: 0.05,
                duration: 3,
                ease: "sine"
            },
            {
                type: "move",
                axis: "x",
                speed: 0.05,
                delay: 1.2,
                ease: "cubic",
                pause: 0.3,
                duration: 3
            },
            {
                type: "rotate",
                degreesY: -10,
                duration: 4,
                ease: "sine",
                loop: "true",
                degreesX: 40
            },
            {
                type: "rotate",
                degreesY: 0,
                duration: 2,
                ease: "sine",
                loop: "true",
                degreesZ: 20,
                degreesX: -10,
                hold: 0.8
            }
        ]
    },
    {
        id: "obj_15",
        src: "symbols/0229 - tehsra.gif",
        w: 0.25,
        h: 0.25,
        pos: {
            x: -0.739951537460283,
            y: 0.6598449419970314,
            z: 0.9062902878278098
        },
        rotation: {
            x: 0,
            y: 120,
            z: 0
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "drift",
                amp: 0.005,
                duration: 3,
                axis: "x",
                ease: "sine",
                pause: 1
            },
            {
                type: "rotate",
                degreesY: -106,
                duration: 4,
                ease: "sine",
                loop: "true",
                degreesX: 60
            },
            {
                type: "rotate",
                degreesY: 0,
                duration: 7,
                ease: "cubic",
                loop: "true",
                degreesZ: 30,
                hold: 0.6
            },
            {
                type: "move",
                axis: "z",
                speed: 0.05,
                direction: -1
            },
            {
                type: "move",
                axis: "y",
                speed: 0.09
            }
        ]
    },
    {
        id: "obj_17",
        src: "symbols/0134 - erear.gif",
        w: 0.425,
        h: 0.425,
        pos: {
            x: -0.7,
            y: 1.6337262549804157,
            z: -0.911039086124788
        },
        rotation: {
            x: 40,
            y: 80,
            z: 0
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "float",
                amp: 0.007,
                duration: 2.5,
                ease: "sine"
            },
            {
                type: "rotate",
                degreesY: -80,
                duration: 7,
                ease: "sine",
                loop: "true",
                degreesX: 40,
                degreesZ: 15
            },
            {
                type: "move",
                axis: "y",
                speed: 0.04,
                direction: -1
            },
            {
                type: "move",
                axis: "x",
                speed: 0.09,
                direction: -1
            },
            {
                type: "rotate",
                degreesY: 360,
                duration: 7,
                ease: "sine",
                loop: "true",
                delay: 2,
                hold: 150
            }
        ]
    },
    {
        id: "obj_18",
        src: "symbols/0124 - aljt.gif",
        w: 0.4,
        h: 0.4,
        pos: {
            x: -1,
            y: 1.96638368951844,
            z: 0.6318191497160738
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "move",
                axis: "x",
                speed: 0.05,
                direction: -1,
                duration: 1.82,
                delay: 1.1,
                pause: 0.63
            },
            {
                type: "rotate",
                degreesY: -40,
                duration: 4,
                ease: "sine",
                loop: "true",
                degreesZ: 70,
                delay: 0.8,
                hold: 0
            }
        ]
    },
    {
        id: "obj_20",
        src: "symbols/0038 - flherd.gif",
        w: 0.15,
        h: 0.15,
        pos: {
            x: 0.6036446145295666,
            y: 0.8815196461766213,
            z: -1
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "spin",
                degrees: 360,
                duration: 3,
                axis: "x",
                ease: "sine",
                pause: 0.1
            },
            {
                type: "rotate",
                degreesY: -100,
                duration: 5,
                ease: "sine",
                loop: "true",
                degreesX: 0,
                degreesZ: -30,
                hold: 0.1
            },
            {
                type: "move",
                axis: "x",
                speed: 0.15
            }
        ]
    },
    {
        id: "obj_21",
        src: "symbols/0038 - flherd.gif",
        w: 0.15,
        h: 0.15,
        pos: {
            x: 0.7036446145295666,
            y: 0.9315196461766213,
            z: -0.9
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "spin",
                degrees: 360,
                duration: 3,
                axis: "x",
                ease: "sine",
                pause: 0.1
            },
            {
                type: "rotate",
                degreesY: 100,
                duration: 5,
                ease: "sine",
                loop: "true",
                degreesX: 0,
                degreesZ: -30
            },
            {
                type: "move",
                axis: "x",
                speed: 0.2
            }
        ]
    },
    {
        id: "obj_22",
        src: "symbols/0038 - flherd.gif",
        w: 0.2,
        h: 0.2,
        pos: {
            x: 0.7036446145295666,
            y: 0.9315196461766213,
            z: -0.9
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "spin",
                degrees: 360,
                duration: 4,
                axis: "x",
                ease: "sine",
                pause: 0.1,
                direction: -1
            },
            {
                type: "rotate",
                degreesY: -100,
                duration: 5,
                ease: "sine",
                loop: "true",
                degreesX: 0,
                degreesZ: -30,
                hold: 0.1
            },
            {
                type: "move",
                axis: "x",
                speed: 0.3
            }
        ]
    },
    {
        id: "obj_23",
        src: "symbols/0038 - flherd.gif",
        w: 0.1,
        h: 0.1,
        pos: {
            x: 0,
            y: 1.9815196461766214,
            z: 0.8
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "spin",
                degrees: 360,
                duration: 4,
                axis: "x",
                ease: "sine",
                pause: 0.1,
                direction: -1
            },
            {
                type: "rotate",
                degreesY: -100,
                duration: 5,
                ease: "sine",
                loop: "true",
                degreesX: 0,
                degreesZ: -30,
                hold: 0.1
            },
            {
                type: "move",
                axis: "x",
                speed: 0.3
            }
        ]
    },
    {
        id: "obj_24",
        src: "symbols/0038 - flherd.gif",
        w: 0.15,
        h: 0.15,
        pos: {
            x: 0.1,
            y: 2.315196461766214,
            z: 0.9
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "spin",
                degrees: 360,
                duration: 2,
                axis: "x",
                ease: "sine",
                pause: 0.1,
                direction: 1
            },
            {
                type: "rotate",
                degreesY: 50,
                duration: 4,
                ease: "sine",
                loop: "true",
                degreesX: 0,
                degreesZ: -30,
                hold: 0
            },
            {
                type: "move",
                axis: "x",
                speed: 0.2
            }
        ]
    },
    {
        id: "obj_25",
        src: "symbols/0021 - orgdem.gif",
        w: 0.25,
        h: 0.25,
        pos: {
            x: 0.3,
            y: 1.8,
            z: -0.8
        },
        rotation: {
            x: 130,
            y: 60,
            z: 0
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "float",
                amp: 0.1,
                duration: 6,
                ease: "sine",
                pause: 0.1,
                direction: -1
            },
            {
                type: "float",
                amp: 0.005,
                duration: 2.3,
                ease: "sine",
                axis: "x",
                delay: 0.3,
                direction: -1
            },
            {
                type: "rotate",
                degreesX: -40,
                degreesZ: 6,
                duration: 2.2,
                ease: "sine",
                loop: true,
                delay: 0.5
            },
            {
                type: "rotate",
                degreesY: -25,
                degreesZ: 20,
                duration: 3.82,
                ease: "sine",
                loop: true
            },
            {
                type: "move",
                axis: "y",
                speed: 0.05
            }
        ]
    },
    {
        id: "obj_26",
        src: "symbols/0311 - kjes.gif",
        w: 0.25,
        h: 0.25,
        pos: {
            x: 0.885003725257866,
            y: 0.8923859013161832,
            z: 0.2769059947682746
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "spin",
                degrees: 20,
                duration: 2,
                axis: "z",
                ease: "elastic",
                direction: -1,
                delay: 1.4
            },
            {
                type: "spin",
                degrees: 360,
                duration: 9,
                axis: "y",
                ease: "none"
            },
            {
                type: "rotate",
                degreesY: 40,
                duration: 4,
                ease: "sine",
                loop: "true",
                degreesX: -80
            },
            {
                type: "move",
                axis: "y",
                speed: 0.04
            },
            {
                type: "move",
                axis: "z",
                speed: 0.07
            }
        ]
    },
    {
        id: "obj_27",
        src: "symbols/0023 - stirkel.gif",
        w: 0.25,
        h: 0.25,
        pos: {
            x: 0.011,
            y: 1.931892353907365,
            z: -0.825
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "spin",
                degrees: 360,
                duration: 4,
                axis: "x",
                ease: "none",
                pause: 0.2
            },
            {
                type: "rotate",
                degreesY: 100,
                duration: 3,
                ease: "sine",
                loop: "true",
                degreesZ: 7,
                degreesX: 0
            },
            {
                type: "move",
                axis: "y",
                speed: 0.6
            }
        ]
    },
    {
        id: "obj_29",
        src: "symbols/0023 - stirkel.gif",
        w: 0.2,
        h: 0.2,
        pos: {
            x: -0.957,
            y: 1.31892353907365,
            z: 0.337
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "spin",
                degrees: 360,
                duration: 4,
                axis: "x",
                ease: "none",
                pause: 0.1,
                direction: -1
            },
            {
                type: "rotate",
                degreesY: -100,
                duration: 3,
                ease: "sine",
                loop: "true",
                degreesZ: 7,
                degreesX: 0,
                hold: 0.1
            },
            {
                type: "move",
                axis: "y",
                speed: 0.6
            }
        ],
        rotation: {
            x: 40,
            y: 500,
            z: 0
        }
    },
    {
        id: "obj_31",
        src: "symbols/0124 - aljt.gif",
        w: 0.27,
        h: 0.27,
        pos: {
            x: -0.349,
            y: 2.0663836895184398,
            z: -0.677
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true,
                delay: 0.3
            },
            {
                type: "move",
                axis: "x",
                speed: 0.05,
                direction: -1,
                duration: 1.82,
                delay: 1.4,
                pause: 0.63
            },
            {
                type: "rotate",
                degreesY: -40,
                duration: 4,
                ease: "sine",
                loop: "true",
                degreesZ: -70,
                delay: 1.2,
                hold: 0
            }
        ],
        rotation: {
            x: 0,
            y: 200,
            z: 40
        }
    },
    {
        id: "obj_33",
        src: "symbols/0311 - kjes.gif",
        w: 0.2,
        h: 0.2,
        pos: {
            x: -0.428,
            y: 1,
            z: -0.868
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true,
                delay: 0.4
            },
            {
                type: "spin",
                degrees: 20,
                duration: 2,
                axis: "z",
                ease: "elastic",
                direction: -1,
                delay: 1.8
            },
            {
                type: "spin",
                degrees: 360,
                duration: 9,
                axis: "y",
                ease: "none"
            },
            {
                type: "rotate",
                degreesY: 40,
                duration: 4,
                ease: "sine",
                loop: "true",
                degreesX: -80
            },
            {
                type: "move",
                axis: "y",
                speed: 0.04
            },
            {
                type: "move",
                axis: "z",
                speed: 0.07
            }
        ],
        rotation: {
            x: -90,
            y: 100,
            z: 90
        }
    },
    {
        id: "obj_36",
        src: "symbols/0014 - benrod.gif",
        w: 0.25,
        h: 0.25,
        pos: {
            x: 1.057,
            y: 2,
            z: -0.244
        },
        rotation: {
            x: -100,
            y: 200,
            z: 200
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "move",
                axis: "y",
                speed: 0.05,
                direction: -1,
                pause: 0.3,
                duration: 2,
                delay: 0.4,
                ease: "sine"
            },
            {
                type: "spin",
                degrees: 360,
                duration: 10,
                axis: "y",
                ease: "none",
                direction: 1
            },
            {
                type: "rotate",
                degreesX: -90,
                duration: 2,
                ease: "sine",
                loop: true,
                delay: 0.4,
                hold: 0.3
            }
        ]
    },
    {
        id: "obj_37",
        src: "symbols/0229 - tehsra.gif",
        w: 0.25,
        h: 0.25,
        pos: {
            x: -0.971,
            y: 2.594302361377106,
            z: 0.445
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "float",
                amp: 0.08,
                duration: 4,
                ease: "sine"
            },
            {
                type: "spin",
                degrees: 360,
                duration: 5,
                axis: "y",
                ease: "none",
                delay: 0.96
            },
            {
                type: "rotate",
                degreesY: 10,
                duration: 2,
                ease: "sine",
                loop: "true",
                degreesX: -70,
                hold: 3,
                degreesZ: 5
            },
            {
                type: "rotate",
                degreesY: 10,
                duration: 5,
                ease: "sine",
                loop: "true",
                degreesZ: 30
            },
            {
                type: "move",
                axis: "x",
                speed: 0.3
            }
        ]
    },
    {
        id: "obj_38",
        src: "symbols/0229 - tehsra.gif",
        w: 0.1,
        h: 0.1,
        pos: {
            x: 0.191,
            y: 2.6443023613771057,
            z: 0.896
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true,
                delay: 0.2
            },
            {
                type: "float",
                amp: 0.08,
                duration: 7,
                ease: "sine"
            },
            {
                type: "spin",
                degrees: 360,
                duration: 3,
                axis: "y",
                ease: "none"
            },
            {
                type: "rotate",
                degreesY: 0,
                duration: 7,
                ease: "sine",
                loop: "true",
                degreesX: 200,
                hold: 3
            },
            {
                type: "rotate",
                degreesY: 0,
                duration: 4,
                ease: "sine",
                loop: "true",
                degreesZ: -100
            },
            {
                type: "move",
                axis: "x",
                speed: 0.08
            }
        ],
        rotation: {
            x: 200,
            y: 30,
            z: 0
        }
    },
    {
        id: "obj_39",
        src: "symbols/0229 - tehsra.gif",
        w: 0.2,
        h: 0.2,
        pos: {
            x: -0.009,
            y: 1.9943023613771056,
            z: 0.996
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true,
                delay: 0.2
            },
            {
                type: "float",
                amp: 0.08,
                duration: 7,
                ease: "sine"
            },
            {
                type: "spin",
                degrees: 360,
                duration: 5,
                axis: "y",
                ease: "none",
                direction: -1
            },
            {
                type: "rotate",
                degreesY: 0,
                duration: 2,
                ease: "sine",
                loop: "true",
                degreesX: -100,
                hold: 3,
                delay: 1
            },
            {
                type: "rotate",
                degreesY: 0,
                duration: 5,
                ease: "sine",
                loop: "true",
                degreesZ: 60
            },
            {
                type: "move",
                axis: "x",
                speed: 0.09,
                pause: 0.5
            }
        ],
        rotation: {
            x: 0,
            y: 300,
            z: 200
        }
    },
    {
        id: "obj_41",
        src: "symbols/0228 - boloop.gif",
        w: 0.25,
        h: 0.25,
        pos: {
            x: -1.051,
            y: 0.6280975477148752,
            z: 0.264
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "breathe",
                amp: 0.05,
                duration: 3,
                ease: "sine"
            },
            {
                type: "move",
                axis: "x",
                speed: 0.05,
                delay: 1.2,
                ease: "cubic",
                pause: 0.3,
                duration: 3
            },
            {
                type: "rotate",
                degreesY: -10,
                duration: 3.4,
                ease: "sine",
                loop: "true",
                degreesX: 40
            },
            {
                type: "rotate",
                degreesY: 0,
                duration: 20,
                ease: "sine",
                loop: "true",
                degreesZ: 20,
                degreesX: 10,
                hold: 0.8
            }
        ],
        rotation: {
            x: 20,
            y: 120,
            z: 0
        }
    },
    {
        id: "obj_42",
        src: "symbols/0105 - aphoon.gif",
        w: 0.4,
        h: 0.4,
        pos: {
            x: -0.765,
            y: 2.199632433970949,
            z: 0.46
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "rotate",
                degreesY: 300,
                duration: 8,
                ease: "bounce",
                loop: "true",
                hold: 0.4,
                delay: 0.2
            },
            {
                type: "spin",
                degrees: 360,
                duration: 15,
                axis: "z",
                ease: "none"
            },
            {
                type: "move",
                axis: "y",
                speed: 0.05
            }
        ]
    },
    {
        id: "obj_43",
        src: "symbols/0311 - kjes.gif",
        w: 0.2,
        h: 0.2,
        pos: {
            x: 0.449,
            y: 2,
            z: 0.564
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true,
                delay: 0.4
            },
            {
                type: "spin",
                degrees: 20,
                duration: 5,
                axis: "z",
                ease: "back",
                direction: -1,
                delay: 1.8
            },
            {
                type: "spin",
                degrees: 360,
                duration: 9,
                axis: "y",
                ease: "none"
            },
            {
                type: "rotate",
                degreesY: 40,
                duration: 4,
                ease: "sine",
                loop: "true",
                degreesX: -80
            },
            {
                type: "move",
                axis: "y",
                speed: 0.04
            },
            {
                type: "move",
                axis: "z",
                speed: 0.07
            }
        ],
        rotation: {
            x: -90,
            y: 100,
            z: 90
        }
    },
    {
        id: "obj_44",
        src: "symbols/0311 - kjes.gif",
        w: 0.15,
        h: 0.15,
        pos: {
            x: -0.681,
            y: 1.1,
            z: 0.625
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true,
                delay: 0.4
            },
            {
                type: "spin",
                degrees: 20,
                duration: 2,
                axis: "z",
                ease: "elastic",
                direction: 1,
                delay: 1.8
            },
            {
                type: "spin",
                degrees: 360,
                duration: 13,
                axis: "y",
                ease: "none"
            },
            {
                type: "rotate",
                degreesY: 40,
                duration: 3,
                ease: "sine",
                loop: "true",
                degreesX: -80
            },
            {
                type: "move",
                axis: "y",
                speed: 0.04
            },
            {
                type: "move",
                axis: "z",
                speed: 0.07
            }
        ],
        rotation: {
            x: 12,
            y: 200,
            z: 90
        }
    },
    {
        id: "obj_45",
        src: "symbols/0308 - ækoj.gif",
        w: 0.5,
        h: 0.5,
        pos: {
            x: 0.12,
            y: 2.73937717201051,
            z: -0.924
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true,
                delay: 0.3
            },
            {
                type: "move",
                axis: "x",
                speed: 0.05,
                direction: -1,
                delay: 1.1,
                duration: 2,
                pause: 1.25
            },
            {
                type: "move",
                axis: "y",
                speed: 0.05,
                delay: 1.1,
                duration: 2,
                pause: 1.25
            },
            {
                type: "spin",
                degrees: 360,
                duration: 9,
                axis: "y",
                ease: "none",
                delay: 0.3
            },
            {
                type: "spin",
                degrees: 360,
                duration: 30,
                axis: "z",
                ease: "none",
                delay: 0.3
            }
        ],
        rotation: {
            x: 120,
            y: 50,
            z: 0
        }
    },
    {
        id: "obj_46",
        src: "symbols/0308 - ækoj.gif",
        w: 0.25,
        h: 0.25,
        pos: {
            x: 0.529,
            y: 0.9973937717201051,
            z: 0.808
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "move",
                axis: "x",
                speed: 0.05,
                direction: -1,
                delay: 0.8,
                duration: 2,
                pause: 1.25
            },
            {
                type: "move",
                axis: "y",
                speed: 0.05,
                delay: 0.8,
                duration: 2,
                pause: 1.25
            },
            {
                type: "spin",
                degrees: 360,
                duration: 9,
                axis: "y",
                ease: "none"
            },
            {
                type: "spin",
                degrees: 360,
                duration: 30,
                axis: "z",
                ease: "none"
            }
        ]
    },
    {
        id: "obj_47",
        src: "symbols/0023 - stirkel.gif",
        w: 0.43,
        h: 0.43,
        pos: {
            x: 0.954,
            y: 2.5,
            z: -0.02
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "spin",
                degrees: 360,
                duration: 5,
                axis: "x",
                ease: "quartOut",
                pause: 0.2
            },
            {
                type: "rotate",
                degreesY: 100,
                duration: 3,
                ease: "sine",
                loop: "true",
                degreesZ: 17,
                degreesX: 0,
                hold: 0.4
            },
            {
                type: "move",
                axis: "y",
                speed: 0.5
            },
            {
                type: "spin",
                degrees: 360,
                duration: 40,
                axis: "x",
                ease: "none"
            }
        ]
    },
    {
        id: "obj_48",
        src: "symbols/0023 - stirkel.gif",
        w: 0.33,
        h: 0.33,
        pos: {
            x: -0.653,
            y: 1.81892353907365,
            z: 0.743
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true,
                delay: 0.2
            },
            {
                type: "spin",
                degrees: 360,
                duration: 7,
                axis: "x",
                ease: "none",
                pause: 0.2
            },
            {
                type: "rotate",
                degreesY: 100,
                duration: 2.5,
                ease: "sine",
                loop: "true",
                degreesZ: 7,
                degreesX: 0,
                hold: 0.2
            },
            {
                type: "move",
                axis: "y",
                speed: 0.6
            }
        ],
        rotation: {
            x: 70,
            y: 140,
            z: 0
        }
    },
    {
        id: "obj_50",
        src: "symbols/0149 - borrap.gif",
        w: 0.1,
        h: 0.1,
        pos: {
            x: 0.931,
            y: 2.985612965321252,
            z: -0.09
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "spin",
                degrees: 360,
                duration: 5,
                axis: "x",
                ease: "none"
            },
            {
                type: "rotate",
                degreesY: 70,
                duration: 4,
                ease: "expo",
                loop: "true",
                degreesZ: -20,
                hold: 0.6
            },
            {
                type: "move",
                axis: "y",
                speed: 0.05
            }
        ]
    },
    {
        id: "obj_51",
        src: "symbols/0149 - borrap.gif",
        w: 0.15,
        h: 0.15,
        pos: {
            x: 0.215,
            y: 2.035612965321252,
            z: 1.138
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "spin",
                degrees: 360,
                duration: 5,
                axis: "x",
                ease: "none",
                direction: -1
            },
            {
                type: "rotate",
                degreesY: 70,
                duration: 3,
                ease: "expo",
                loop: "true",
                degreesZ: -20,
                hold: 0.6
            },
            {
                type: "move",
                axis: "y",
                speed: 0.05
            }
        ]
    },
    {
        id: "obj_52",
        src: "symbols/0315 - pejhes.gif",
        w: 0.19,
        h: 0.19,
        pos: {
            x: 0.188,
            y: 1.8731011554353925,
            z: -1.058
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "move",
                axis: "y",
                speed: 0.05,
                delay: 0.6,
                pause: 1
            },
            {
                type: "move",
                axis: "y",
                speed: 0.007,
                ease: "quadIn"
            },
            {
                type: "spin",
                degrees: 360,
                duration: 9,
                axis: "y",
                ease: "none",
                pause: 0.9
            },
            {
                type: "rotate",
                degreesY: 20,
                duration: 7,
                ease: "back",
                loop: "true",
                degreesZ: -70
            }
        ]
    },
    {
        id: "obj_54",
        src: "symbols/0288 - irlij.gif",
        w: 0.25,
        h: 0.25,
        pos: {
            x: -0.717,
            y: 0.8369705280435452,
            z: -0.748
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "rotate",
                degreesY: -90,
                duration: 4,
                ease: "sine",
                loop: "true",
                degreesX: -60,
                hold: 0.3,
                delay: 0.8
            },
            {
                type: "drift",
                amp: 0.007,
                duration: 2,
                axis: "x",
                ease: "sine"
            },
            {
                type: "move",
                axis: "y",
                speed: 0.03
            },
            {
                type: "move",
                axis: "x",
                speed: 0.05
            }
        ]
    },
    {
        id: "obj_55",
        src: "symbols/0288 - irlij.gif",
        w: 0.2,
        h: 0.2,
        pos: {
            x: 0.688,
            y: 2.886970528043545,
            z: -0.627
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "rotate",
                degreesY: 90,
                duration: 4.2,
                ease: "sine",
                loop: "true",
                degreesX: 60,
                hold: 0.3,
                delay: 0.4
            },
            {
                type: "drift",
                amp: 0.02,
                duration: 2,
                axis: "x",
                ease: "sine"
            },
            {
                type: "move",
                axis: "y",
                speed: 0.03
            },
            {
                type: "move",
                axis: "x",
                speed: 0.05
            }
        ]
    },
    {
        id: "obj_56",
        src: "symbols/0315 - pejhes.gif",
        w: 0.19,
        h: 0.19,
        pos: {
            x: -0.909,
            y: 1.231011554353925,
            z: -0.469
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true,
                delay: 0.7
            },
            {
                type: "move",
                axis: "y",
                speed: 0.05,
                delay: 1.6,
                pause: 1
            },
            {
                type: "move",
                axis: "y",
                speed: 0.007,
                ease: "quadIn"
            },
            {
                type: "spin",
                degrees: 360,
                duration: 9,
                axis: "y",
                ease: "none",
                pause: 0.9,
                direction: -1
            },
            {
                type: "rotate",
                degreesY: 20,
                duration: 7,
                ease: "back",
                loop: "true",
                degreesZ: -70,
                degreesX: 13
            }
        ]
    },
    {
        id: "obj_59",
        src: "symbols/0311 - kjes.gif",
        w: 0.15,
        h: 0.15,
        pos: {
            x: -0.110000000000001,
            y: 0.400000000000001,
            z: 0.925
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true,
                delay: 0.4
            },
            {
                type: "spin",
                degrees: 20,
                duration: 2,
                axis: "z",
                ease: "elastic",
                direction: 1,
                delay: 1.8
            },
            {
                type: "spin",
                degrees: 360,
                duration: 13,
                axis: "y",
                ease: "none",
                direction: -1
            },
            {
                type: "rotate",
                degreesY: 40,
                duration: 3.4,
                ease: "sine",
                loop: "true",
                degreesX: -80
            },
            {
                type: "move",
                axis: "y",
                speed: 0.03
            },
            {
                type: "move",
                axis: "z",
                speed: 0.07
            }
        ],
        rotation: {
            x: 12,
            y: 200,
            z: 90
        }
    },
    {
        id: "obj_60",
        src: "symbols/0149 - borrap.gif",
        w: 0.15,
        h: 0.15,
        pos: {
            x: 0.315,
            y: 0.2856129653212516,
            z: 1.238
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "spin",
                degrees: 360,
                duration: 5,
                axis: "x",
                ease: "none",
                direction: -1
            },
            {
                type: "rotate",
                degreesY: 70,
                duration: 3,
                ease: "expo",
                loop: "true",
                degreesZ: -20,
                hold: 0.6
            },
            {
                type: "move",
                axis: "y",
                speed: 0.05
            }
        ]
    },
    {
        id: "obj_61",
        src: "symbols/0023 - stirkel.gif",
        w: 0.2,
        h: 0.2,
        pos: {
            x: 1.054,
            y: 0.55,
            z: 0.08
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "spin",
                degrees: 360,
                duration: 5,
                axis: "x",
                ease: "quartOut",
                pause: 0.6,
                direction: -1
            },
            {
                type: "rotate",
                degreesY: 100,
                duration: 2,
                ease: "sine",
                loop: "true",
                degreesZ: 17,
                degreesX: 0,
                hold: 0
            },
            {
                type: "move",
                axis: "y",
                speed: 0.4
            },
            {
                type: "spin",
                degrees: 360,
                duration: 30,
                axis: "x",
                ease: "none"
            },
            {
                type: "move",
                axis: "y",
                speed: 0.05,
                direction: -1,
                duration: 3,
                delay: 10,
                cycles: 1
            }
        ]
    },
    {
        id: "obj_62",
        src: "symbols/0315 - pejhes.gif",
        w: 0.09,
        h: 0.09,
        pos: {
            x: 0.28800000000000003,
            y: 0.2231011554353925,
            z: -0.9580000000000001
        },
        onStart: [
            {
                type: "gifPlay",
                loop: true
            },
            {
                type: "move",
                axis: "y",
                speed: 0.05,
                delay: 0.6,
                pause: 1
            },
            {
                type: "move",
                axis: "y",
                speed: 0.007,
                ease: "quadIn"
            },
            {
                type: "spin",
                degrees: 360,
                duration: 9,
                axis: "y",
                ease: "none",
                pause: 0.9
            },
            {
                type: "rotate",
                degreesY: 20,
                duration: 7,
                ease: "back",
                loop: "true",
                degreesZ: -70
            }
        ]
    }
]

};
